-- Remote migration version: 20260427170350
-- Remote migration name: 00009_parental_consent
-- Mapped legacy migration: 00009_parental_consent.sql
-- Legacy archive path: supabase/migration_archive/legacy_pre_baseline/00009_parental_consent.sql
-- Historical SQL execution is recorded in the existing remote migration history.
-- This comments-only anchor does not recreate or claim to execute that SQL.
-- The canonical baseline supersedes historical schema evolution.
-- DO NOT REPLAY historical SQL.
