-- Remote migration version: 20260502120308
-- Remote migration name: 00018_under13_preapproval_guard
-- Mapped legacy migration: 00018_under13_preapproval_guard.sql
-- Legacy archive path: supabase/migration_archive/legacy_pre_baseline/00018_under13_preapproval_guard.sql
-- Historical SQL execution is recorded in the existing remote migration history.
-- This comments-only anchor does not recreate or claim to execute that SQL.
-- The canonical baseline supersedes historical schema evolution.
-- DO NOT REPLAY historical SQL.
