-- Remote migration version: 20260502113939
-- Remote migration name: 00016_child_profiles_email_preapproval
-- Mapped legacy migration: 00016_child_profiles_email_preapproval.sql
-- Legacy archive path: supabase/migration_archive/legacy_pre_baseline/00016_child_profiles_email_preapproval.sql
-- Historical SQL execution is recorded in the existing remote migration history.
-- This comments-only anchor does not recreate or claim to execute that SQL.
-- The canonical baseline supersedes historical schema evolution.
-- DO NOT REPLAY historical SQL.
