-- Remote migration version: 20260428202546
-- Remote migration name: 00012_profiles_rls_metadata_upsert
-- Mapped legacy migration: 00012_profiles_rls_metadata_upsert.sql
-- Legacy archive path: supabase/migration_archive/legacy_pre_baseline/00012_profiles_rls_metadata_upsert.sql
-- Historical SQL execution is recorded in the existing remote migration history.
-- This comments-only anchor does not recreate or claim to execute that SQL.
-- The canonical baseline supersedes historical schema evolution.
-- DO NOT REPLAY historical SQL.
