-- Remote migration version: 20260502182210
-- Remote migration name: idempotent_link_child_account
-- Mapped legacy migration: 00019_idempotent_link_child_account.sql
-- Legacy archive path: supabase/migration_archive/legacy_pre_baseline/00019_idempotent_link_child_account.sql
-- Historical SQL execution is recorded in the existing remote migration history.
-- This comments-only anchor does not recreate or claim to execute that SQL.
-- The canonical baseline supersedes historical schema evolution.
-- DO NOT REPLAY historical SQL.
